# Set up the Rust toolchain.
language: rust

os:
- linux
- osx
- windows

 # Allow for occasional compiler breakage on nightly Rust.
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: stable
      script:
        - cargo test --all --all-features --locked
        - rustup component add rustfmt-preview
        - cargo fmt -- --write-mode=diff
    - rust: beta
      script:
        - cargo test --all --all-features --locked
    - rust: nightly
      script:
        - cargo test --all --all-features --locked
