# Set up the Rust toolchain.
language: rust

os:
- linux
- osx
- windows

rust:
  # - stable
  # - beta
  - nightly

 # Allow for occasional compiler breakage on nightly Rust.
matrix:
  fast_finish: true
  include:
    - rust: nightly
      script:
        - rustup component add rustfmt-preview
        - cargo fmt -- --check
  
script:
  - cargo test --all --all-features --locked

