[package]
name = "clique"
version = "0.1.0"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]

[dependencies]
futures = "*"
bytes = "*"
serde = { version = "1.0" }
serde_derive = "1.0"
serde_json="*"
tokio = "0.1"
uuid = { version = "*", features= ["v4", "serde"]}
log = "*"
pretty_env_logger = "*"

